### PR TITLE
Changes for Magento 2.3

### PR DESCRIPTION
**Pull request by bst2002git**
Tested on my Magento 2.3 installation.
With Live DHL Business Account (www.dhl-geschaeftskundenportal.de)
Creating Shipping-Label ok.
Transmitting Data into DHL Business Customer Portal also works
Tracking-Code generation etc... works

### CODE REVIEW

**Comment by ngolatka** [comment]
Thanks for the contribution, @bst2002git 

However, we are already working on the next release. It is currently only blocked by other change requests which we received from DHL. The actual compatibility with M2.3 is already done in our internal development branch (which unfortunately we can't push to Github).

Keep an eye on issue #44 to stay informed.

**Comment by fwolfst** [comment]
Crazy. Maybe it would make sense to state in the README which contributions are welcome and can be taken into account and how development proceeds. Btw, the Copyright in the README states "2017".

**Comment by ngolatka** [comment]
> Crazy. Maybe it would make sense to state in the README which contributions are welcome and can be taken into account

@fwolfst Did you notice there is a CONTRIBUTING.md?

Maybe I didn't make it totally clear in my previous comment: we are working on the next release _which will include compatibility with M2.3 / PHP 7.2_ (as stated in the issue #44 which I linked).

**Comment by fwolfst** [comment]
> @fwolfst Did you notice there is a CONTRIBUTING.md?

Just saying, it would be good to state in that file something like: "development happens behind the doors, before working on an issue please make sure we are not already working on it. Please respect that for whatever reasons we cannot show you the current state of development.".

But ack, that this was mentioned in/for #44 .

**Comment by ngolatka** [comment]
> before working on an issue please make sure we are not already working on it

That would be a bit impractical, wouldn't it? The rule of thumb is: contributions and suggestions are totally welcome! But we need to discuss with DHL if they want to see a particular change / feature in the official module - unless it's a bugifx, that of course needs no approval.

> Please respect that for whatever reasons we cannot show you the current state of development

We can't show the current status or roadmap _on Github_, because things change quite frequently. However, if asked about a specific thing, we will reply (as in issue #44).

We can only push the master to Github, because it needs to be tested and approved by DHL before going public. If people used the develop branch in their production systems (which sooner or later would happen), things could go awry. That's just too risky, and also a nightmare for the tech support team.

**Comment by fwolfst** [comment]
> We can only push the master to Github, because it needs to be tested and approved by DHL before going public. If people used the develop branch in their production systems (which sooner or later would happen), things could go awry. That's just too risky, and also a nightmare for the tech support team.

> we need to discuss with DHL if they want to see a particular change / feature in the official module - unless it's a bugifx, that of course needs no approval.

Thanks for being open about discussing and sharing that stuff. I'd find the two facts above interesting and relevant enough to share them in the README or CONTRIBUTION. Anyway, just my 2 cents, issue closed.

**Pull request closed without merging**
